// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "CanYouHearMe",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "CanYouHearMe",
            targets: ["AppModule"],
            bundleIdentifier: "com.vzazulin.CanYouHearMe",
            teamIdentifier: "VN2RLNZA3K",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            capabilities: [
                .speechRecognition(purposeString: "To turn your voice into text, CanYouHearMe needs access to speech recognition. Your words are processed securely on your device – no internet required."),
                .microphone(purposeString: "CanYouHearMe needs access to your microphone to record your message. Don't worry – everything stays private and runs entirely on your device.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)